import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import Aos from "./aos/aos";
import "maplibre-gl/dist/maplibre-gl.css";
import { Smooch_Sans } from "next/font/google";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Marion Trade",
  description: "Generated by create next app",
};


const smoochSans = Smooch_Sans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${smoochSans.className} h-full antialiased`}
    >
      <body className=" bg-[#0e0f10] flex flex-col">
        <Aos />
        {children}
        <Toaster />
      </body>
    </html>
  );
}


